### ISSUE TITLE
Authentication using office365 accounts

### ISSUE THREAD

**Issue by slawekww** [MicrosoftDocs/azure-docs.pl-pl#377]
I work with organization of 500+ users who already have Office365 accounts.
Please advise if it is possible to assign them as readers to ACR created by my subscription/resource group without creating Azure subscriptions for them. Docker login is expected to work for them or azure cli login.
Goal is that they need to use ACR as service, they do not need to manage it but authentication must be supported by Office365 (Active Directory).
If it is possible, please let me know how to setup it on ACR Access Control.

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: df40e112-6cf4-f6ce-4d82-d36bbd561405
* Version Independent ID: a68e6e7b-dfa2-8640-0a43-cd15f24facdb
* Content: [Uwierzytelnianie przy użyciu usługi Azure Container Registry](https://docs.microsoft.com/pl-pl/azure/container-registry/container-registry-authentication#feedback)
* Content Source: [articles/container-registry/container-registry-authentication.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/master/articles/container-registry/container-registry-authentication.md)
* Service: **container-registry**
* GitHub Login: @dlepow
* Microsoft Alias: **danlep**

**Comment by srvbpigh** [comment]
Hello, @slawekww
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @slawekww 

Your contribution is much appreciated. Our team can only answer feedback related to the documentation.
Please kindly log your product feedback by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles. 
	
Kind regards,
Microsoft DOCS International Team
