### ISSUE TITLE
Machine translation/No hover function

### ISSUE THREAD

**Issue by Ckociecki** [MicrosoftDocs/azure-docs.pl-pl#39]
The Polish text on this page is very bad and should have been marked as machine translation. Additionally, original text should be made available on mouse hover.

**Comment by SunnyDeng** [comment]
@Ckociecki Thank you for the contribution! We recently enabled hove over function, please check. However, could you please still tell the URL when you mention 'this page' at 11/8?

**Comment by SunnyDeng** [comment]
@Ckociecki ping

**Comment by SunnyDeng** [comment]
Closed as the contributor no respond. @Ckociecki please feel free to re-open if you have further question.
