### ISSUE TITLE
ExecutionContext link - page not found

### ISSUE THREAD

**Issue by karaibek27** [MicrosoftDocs/azure-docs.pl-pl#44]
In section titled "UseCore" link to 'ExecutionContext' page cannot be loaded ( if we modify the link to : https://github.com/Azure/azure-webjobs-sdk-extensions/tree/master/src/WebJobs.Extensions/Extensions there are just Files and Timers). Is Core deleted or moved to other place? 
Thanks for answer :)

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: a4500b14-64b4-4d1b-aae3-f0fd4dde85f2
* Version Independent ID: 8fb75741-37b9-b45f-c0ca-9948ddaf1c06
* Content: [Jak używać zestawu Azure WebJobs SDK](https://docs.microsoft.com/pl-pl/azure/app-service/webjobs-sdk-how-to#manual-trigger)
* Content Source: [articles/app-service/webjobs-sdk-how-to.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/live/articles/app-service/webjobs-sdk-how-to.md)
* Service: **app-service-web**
* GitHub Login: @ggailey777
* Microsoft Alias: **glenga**

**Comment by CeciAc** [comment]
Hello, @karaibek27
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.

Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #19336](https://github.com/MicrosoftDocs/azure-docs/issues/19336) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @karaibek27,

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - V.

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
