### ISSUE TITLE
Invalid reponse error with OpenApi 3.0.1

### ISSUE THREAD

**Issue by ratka6** [MicrosoftDocs/azure-docs.pl-pl#468]
When trying to link openapi.json file, I got "Invalid response" error but with the content of the file as error's body. I uploaded the file to storage account, did all mentioned in the instruction. Is this a problem with OpenApi or with "HTTP + Swagger" action (also happens with trigger)?

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: b8856668-d4f5-0ade-5576-661ada7fcb0e
* Version Independent ID: 291ff6b8-bfcc-786d-6295-eefae7d1b0d2
* Content: [Nawiązywanie połączenia punkty końcowe REST z usługi Azure Logic Apps](https://docs.microsoft.com/pl-pl/azure/connectors/connectors-native-http-swagger#feedback)
* Content Source: [articles/connectors/connectors-native-http-swagger.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/master/articles/connectors/connectors-native-http-swagger.md)
* Service: **logic-apps**
* GitHub Login: @ecfan
* Microsoft Alias: **estfan**

**Comment by srvbpigh** [comment]
Hello, @ratka6
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Issue moved to [MicrosoftDocs/azure-docs #40331](https://github.com/MicrosoftDocs/azure-docs/issues/40331) via [**ZenHub**](https://www.zenhub.com/)

**Comment by CeciAc** [comment]
Hello, @ratka6

Your contribution is much appreciated. Your feedback is related to the original documentation.
Hence, we are migrating this issue to the English repo. Please review the status of the issue here - https://github.com/MicrosoftDocs/azure-docs/issues/40331

We truly appreciate your contribution to our articles. 

Kind regards,
Microsoft DOCS International Team
