### ISSUE TITLE
Code snippet do not work - Translation API 

### ISSUE THREAD

**Issue by GIKroch** [MicrosoftDocs/azure-docs.pl-pl#470]
Hi, 

it may sound crazy but I have literally copied every line of Python which is available for Translation API and I get 404 Error - Resource not found. I have provided subscription key and endpoint as I was supposed to and I have no clue why this is not working. What are the things which may introduce this error. Would be really grateful for any help cause Azure platform is a new thing for me. 

Best wishes,

**Comment by srvbpigh** [comment]
Hello, @GIKroch
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by CeciAc** [comment]
Hello, @GIKroch 

Your contribution is much appreciated. Yet, this feedback is related with product, please kindly log by using the button "Give Product Feedback" at the bottom of the DOCS page.

If you have any feedback related to the documentation, please feel free to log it through this channel.
We truly appreciate your contribution to our articles.
	
Kind regards,
Microsoft DOCS International Team
