### ISSUE TITLE
Deficiencies in the code

### ISSUE THREAD

**Issue by kruczekrobert** [MicrosoftDocs/azure-docs.pl-pl#472]
Hi, I noticed that the code presented here has one line missing to show functionality:

We need to add plt.show() before plt.axis("off") to show a matplot image window with rectangles/polygons :)

Cheers

---
#### Szczegóły dokumentu

⚠ *Nie edytuj tej sekcji. Jest ona wymagana dla docs.microsoft.com ➟ Dołączanie problemu w usłudze GitHub.*

* ID: ab15e2d6-7f06-3037-d47d-2d76fb8456ac
* Version Independent ID: 396d1582-f04b-ad66-88ee-ae614ecd0ece
* Content: [Szybki Start: Wyodrębnianie wydrukowanych tekstu — REST, Python - Azure Cognitive Services](https://docs.microsoft.com/pl-pl/azure/cognitive-services/computer-vision/quickstarts/python-print-text#feedback)
* Content Source: [articles/cognitive-services/Computer-vision/QuickStarts/python-print-text.md](https://github.com/MicrosoftDocs/azure-docs.pl-pl/blob/master/articles/cognitive-services/Computer-vision/QuickStarts/python-print-text.md)
* Service: **cognitive-services**
* Sub-service: **computer-vision**
* GitHub Login: @PatrickFarley
* Microsoft Alias: **pafarley**

**Comment by srvbpigh** [comment]
Hello, @kruczekrobert
 
Thank you for your feedback.
 
We are actively reviewing your comments and will get back to you soon.


Kind regards,
Microsoft DOCS International Team

**Comment by ticianaciminari** [comment]
Issue moved to [MicrosoftDocs/azure-docs #46747](https://github.com/MicrosoftDocs/azure-docs/issues/46747) via [**ZenHub**](https://www.zenhub.com/)

**Comment by srvbpigh** [comment]
Witaj, @kruczekrobert!  

Dziękujemy za Twój wkład. Twoja opinia dotyczy oryginalnej dokumentacji.  

W związku z tym przenosimy ten problem do repozytorium angielskiej wersji językowej. Stan problemu możesz sprawdzić tutaj: https://github.com/MicrosoftDocs/azure-docs/issues/46747.  

Naprawdę doceniamy Twój wkład w nasze artykuły.   

Pozdrawiamy,  
Międzynarodowy zespół witryny Microsoft DOCS
